name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        env GOOS=linux go build -v ./...
        env GOOS=darwin go build -o map_file_reader_macOS -v ./...
        env GOOS=windows go build -o map_file_reader.exe -v ./...

    - name: Test
      run: go test -v ./...
